/*
 * Copyright (c) 2010-2025 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.openhab.binding.rachio.utils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;

/**
 * Deserializes a JSON array into a {@link Map} using the provided key extraction function and value class type.
 * <p>
 * Each element of the JSON array is deserialized into an instance of {@code V} using the provided {@link JsonDeserializationContext}.
 * The key for each map entry is generated by applying the {@code keyFunc} function to the deserialized value.
 * Entries with {@code null} values are ignored.
 * </p>
 *
 * @param json the JSON data being deserialized; expected to be a JSON array
 * @param typeOfT the type of the destination object (ignored in this implementation)
 * @param context the context for deserialization
 * @return a {@link Map} containing keys and values extracted from the JSON array
 * @throws JsonParseException if the input is not a JSON array, the context is {@code null}, or key extraction fails
 *
 * @author Jeff James - Initial contribution
 * 
 * <p><b>Example usage:</b></p>
 * <pre>{@code
 * // Suppose you have a class Device with a getId() method:
 * class Device {
 *     private String id;
 *     public String getId() { return id; }
 * }
 *
 * // Register the deserializer with Gson:
 * Gson gson = new GsonBuilder()
 *     .registerTypeAdapter(
 *         new TypeToken<Map<String, Device>>(){}.getType(),
 *         new JsonArrayToMapSerializer<>(Device::getId, Device.class)
 *     )
 *     .create();
 *
 * // Example JSON array:
 * String json = "[{\"id\":\"dev1\"}, {\"id\":\"dev2\"}]";
 *
 * // Deserialize:
 * Map<String, Device> deviceMap = gson.fromJson(json, new TypeToken<Map<String, Device>>(){}.getType());
 * }</pre>
 *
 * @param <K> the type of keys maintained by the resulting map
 * @param <V> the type of mapped values (elements of the JSON array)
 */
@NonNullByDefault
public class JsonArrayToMapSerializer<K, V> implements JsonDeserializer<Map<K, V>> {
    private final Function<V, K> keyFunc;
    private final Class<V> clazzV;

    public JsonArrayToMapSerializer(Function<V, K> keyFunc, Class<V> clazzV) {
        this.keyFunc = keyFunc;
        this.clazzV = clazzV;
    }

    @Override
    public Map<K, V> deserialize(@Nullable JsonElement json, @Nullable Type typeOfT,
            @Nullable JsonDeserializationContext context) throws JsonParseException {
        if (json == null || !json.isJsonArray() || context == null) {
            throw new JsonParseException("Expected JSON array");
        }

        HashMap<K, V> hashMap = new HashMap<>();

        for (JsonElement element : json.getAsJsonArray()) {
            @Nullable
            V v = context.deserialize(element, clazzV);
            if (v != null) {
                K k;
                try {
                    k = keyFunc.apply(v);
                } catch (IllegalArgumentException | SecurityException e) {
                    throw new JsonParseException(e.getCause());
                }
                hashMap.put(k, v);
            }
        }

        return hashMap;
    }
}
